name: Generate Dramatic Commit Message

on:
  push:
    branches:
      - main  

jobs:
  dramatize_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for amending commits

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3


      - name: Get last commit message
        id: get_commit
        run: |
          LAST_MSG=$(git log -1 --pretty=%B)
          echo "msg=$LAST_MSG" >> $GITHUB_OUTPUT

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
    
      - name: Pull and run Ollama container
        run: |
          docker run -d --name ollama -p 11434:11434 ollama/ollama
        
      - name: Wait for Ollama to be ready
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:11434 | grep -q "ollama"; then
              echo "Ollama is ready!"
              break
            fi
            echo "Waiting for Ollama..."
            sleep 3
          done

      - name: Generate dramatic message with Ollama
        id: dramatic_commit
        run: |
          PROMPT="Rewrite this commit message dramatically: '${{ steps.get_commit.outputs.msg }}'"
          RESPONSE=$(curl -s -X POST http://localhost:11434/api/generate \
          -H "Content-Type: application/json" \
          -d "{\"model\": \"llama3:instruct\", \"prompt\": \"$PROMPT\"}")
    
          COMMIT_MSG=$(echo "$RESPONSE" | jq -r '.response // .completion // ""' | head -n 1)

          echo "Generated message: $COMMIT_MSG"

          # Fallback if empty
          if [ -z "$COMMIT_MSG" ]; then
            COMMIT_MSG="Initial commit - rewritten dramatically!"
          fi

          echo "dramatic_msg=$COMMIT_MSG" >> $GITHUB_OUTPUT


      - name: Set up Git authentication using PAT
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}

      - name: Commit and push the dramatic commit message
        run: |
            git config user.name "Tyson Williams"
            git config user.email "tyson.williams95@gmail.com"
            git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
            
            git status
            git commit --amend -m "${{ steps.dramatic_commit.outputs.dramatic_msg }}"
            git push --force origin main



